[general]
fps_counter = false
audio_offset = 0
visual_offset = 0
language = "ja"
timer_frozen = true
judge_counter = false
nijiiro_notes = false
log_level = 40
fake_online = false
practice_mode_bar_delay = 1
score_method = "shinuchi"

[nameplate_1p]
name = "NeuroCypher"
title = "輻能戰魂"
title_bg = 0
dan = 24
gold = true
rainbow = true

[nameplate_2p]
name = "かつちゃん"
title = "ドンだーデビュー！"
title_bg = 1
dan = -1
gold = false
rainbow = false

[paths]
tja_path = ["Songs"]
skin = "PyTaikoGreen"

[keys]
exit_key = "Q"
borderless_key = "f10"
fullscreen_key = "f11"
pause_key = "space"
back_key = "escape"
restart_key = "f1"

[keys_1p]
left_kat = ["Q", "W", "E", "R"]
left_don = ["A", "S", "D", "F"]
right_don = ["J", "K", "L"]
right_kat = ["U", "I", "O", "P"]

[keys_2p]
left_kat = ["Z"]
left_don = ["X"]
right_don = ["C"]
right_kat = ["V"]

[gamepad]
left_kat = [10]
left_don = [16]
right_don = [17]
right_kat = [12]

[audio]
device_type = 0
sample_rate = 44100
buffer_size = 128

[volume]
sound = 0.7
music = 1.0
voice = 0.6
hitsound = 0.9
attract_mode = 0.6

[video]
fullscreen = false
borderless = false
target_fps = -1
vsync = false
