[general]
fps_counter = false
audio_offset = 0
visual_offset = 0
language = "en"
timer_frozen = true
judge_counter = false
nijiiro_notes = false
log_level = 30
fake_online = false
practice_mode_bar_delay = 1
score_method = "shinuchi"

[nameplate_1p]
name = "どんちゃん"
title = "ドンだーデビュー！"
title_bg = 0
dan = -1
gold = false
rainbow = false

[nameplate_2p]
name = "かつちゃん"
title = "ドンだーデビュー！"
title_bg = 1
dan = -1
gold = false
rainbow = false

[paths]
tja_path = ["Songs"]
skin = "PyTaikoGreen"

[keys]
exit_key = "Q"
borderless_key = "f10"
fullscreen_key = "f11"
pause_key = "space"
back_key = "escape"
restart_key = "f1"

[keys_1p]
left_kat = ["D"]
left_don = ["F"]
right_don = ["J"]
right_kat = ["K"]

[keys_2p]
left_kat = ["Z"]
left_don = ["X"]
right_don = ["C"]
right_kat = ["V"]

[gamepad]
left_kat = [10]
left_don = [16]
right_don = [17]
right_kat = [12]

[audio]
device_type = 0
sample_rate = 44100
buffer_size = 32

[volume]
sound = 1.0
music = 0.0
voice = 1.0
hitsound = 1.0
attract_mode = 1.0

[video]
fullscreen = false
borderless = false
target_fps = -1
vsync = false
